// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dfedata.proto

package dex2fe

import (
	fmt "fmt"
	dex2 "git.bibox.com/dextop/common.git/proto/dex2"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transfer_Action int32

const (
	Transfer_UnknownAction Transfer_Action = 0
	Transfer_Deposit       Transfer_Action = 1
	Transfer_Withdraw      Transfer_Action = 2
)

var Transfer_Action_name = map[int32]string{
	0: "UnknownAction",
	1: "Deposit",
	2: "Withdraw",
}

var Transfer_Action_value = map[string]int32{
	"UnknownAction": 0,
	"Deposit":       1,
	"Withdraw":      2,
}

func (x Transfer_Action) String() string {
	return proto.EnumName(Transfer_Action_name, int32(x))
}

func (Transfer_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{6, 0}
}

// The information of a trading pair.
type PairInfo struct {
	PairId               string   `protobuf:"bytes,1,opt,name=pair_id,json=pairId,proto3" json:"pair_id,omitempty"`
	TimeMs               int64    `protobuf:"varint,2,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	OpenPrice            string   `protobuf:"bytes,3,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	LastPrice            string   `protobuf:"bytes,4,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	Volume_24            string   `protobuf:"bytes,5,opt,name=volume_24,json=volume24,proto3" json:"volume_24,omitempty"`
	Amount_24            string   `protobuf:"bytes,6,opt,name=amount_24,json=amount24,proto3" json:"amount_24,omitempty"`
	Change_24            string   `protobuf:"bytes,7,opt,name=change_24,json=change24,proto3" json:"change_24,omitempty"`
	ChangePercent_24     string   `protobuf:"bytes,8,opt,name=change_percent_24,json=changePercent24,proto3" json:"change_percent_24,omitempty"`
	High_24              string   `protobuf:"bytes,9,opt,name=high_24,json=high24,proto3" json:"high_24,omitempty"`
	Low_24               string   `protobuf:"bytes,10,opt,name=low_24,json=low24,proto3" json:"low_24,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PairInfo) Reset()         { *m = PairInfo{} }
func (m *PairInfo) String() string { return proto.CompactTextString(m) }
func (*PairInfo) ProtoMessage()    {}
func (*PairInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{0}
}

func (m *PairInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PairInfo.Unmarshal(m, b)
}
func (m *PairInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PairInfo.Marshal(b, m, deterministic)
}
func (m *PairInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairInfo.Merge(m, src)
}
func (m *PairInfo) XXX_Size() int {
	return xxx_messageInfo_PairInfo.Size(m)
}
func (m *PairInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PairInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PairInfo proto.InternalMessageInfo

func (m *PairInfo) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *PairInfo) GetTimeMs() int64 {
	if m != nil {
		return m.TimeMs
	}
	return 0
}

func (m *PairInfo) GetOpenPrice() string {
	if m != nil {
		return m.OpenPrice
	}
	return ""
}

func (m *PairInfo) GetLastPrice() string {
	if m != nil {
		return m.LastPrice
	}
	return ""
}

func (m *PairInfo) GetVolume_24() string {
	if m != nil {
		return m.Volume_24
	}
	return ""
}

func (m *PairInfo) GetAmount_24() string {
	if m != nil {
		return m.Amount_24
	}
	return ""
}

func (m *PairInfo) GetChange_24() string {
	if m != nil {
		return m.Change_24
	}
	return ""
}

func (m *PairInfo) GetChangePercent_24() string {
	if m != nil {
		return m.ChangePercent_24
	}
	return ""
}

func (m *PairInfo) GetHigh_24() string {
	if m != nil {
		return m.High_24
	}
	return ""
}

func (m *PairInfo) GetLow_24() string {
	if m != nil {
		return m.Low_24
	}
	return ""
}

type Depth struct {
	PairId string `protobuf:"bytes,1,opt,name=pair_id,json=pairId,proto3" json:"pair_id,omitempty"`
	TimeMs int64  `protobuf:"varint,2,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	// Entries selling the stock token for the cash token. Ascending by price.
	Asks []*DepthEntry `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
	// Entries buying the stock token with the cash token. Descending by price.
	Bids                 []*DepthEntry `protobuf:"bytes,4,rep,name=bids,proto3" json:"bids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Depth) Reset()         { *m = Depth{} }
func (m *Depth) String() string { return proto.CompactTextString(m) }
func (*Depth) ProtoMessage()    {}
func (*Depth) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{1}
}

func (m *Depth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Depth.Unmarshal(m, b)
}
func (m *Depth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Depth.Marshal(b, m, deterministic)
}
func (m *Depth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Depth.Merge(m, src)
}
func (m *Depth) XXX_Size() int {
	return xxx_messageInfo_Depth.Size(m)
}
func (m *Depth) XXX_DiscardUnknown() {
	xxx_messageInfo_Depth.DiscardUnknown(m)
}

var xxx_messageInfo_Depth proto.InternalMessageInfo

func (m *Depth) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *Depth) GetTimeMs() int64 {
	if m != nil {
		return m.TimeMs
	}
	return 0
}

func (m *Depth) GetAsks() []*DepthEntry {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *Depth) GetBids() []*DepthEntry {
	if m != nil {
		return m.Bids
	}
	return nil
}

type DepthEntry struct {
	// The price level of the this entry.
	Price string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	// The total amount of stock token available at this price.
	Amount string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// The total value of the trade which is `price` * `amount`
	TotalValue string `protobuf:"bytes,3,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	// The total value summed up till this price level.
	SumValue             string   `protobuf:"bytes,4,opt,name=sum_value,json=sumValue,proto3" json:"sum_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepthEntry) Reset()         { *m = DepthEntry{} }
func (m *DepthEntry) String() string { return proto.CompactTextString(m) }
func (*DepthEntry) ProtoMessage()    {}
func (*DepthEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{2}
}

func (m *DepthEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepthEntry.Unmarshal(m, b)
}
func (m *DepthEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepthEntry.Marshal(b, m, deterministic)
}
func (m *DepthEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepthEntry.Merge(m, src)
}
func (m *DepthEntry) XXX_Size() int {
	return xxx_messageInfo_DepthEntry.Size(m)
}
func (m *DepthEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_DepthEntry.DiscardUnknown(m)
}

var xxx_messageInfo_DepthEntry proto.InternalMessageInfo

func (m *DepthEntry) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *DepthEntry) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *DepthEntry) GetTotalValue() string {
	if m != nil {
		return m.TotalValue
	}
	return ""
}

func (m *DepthEntry) GetSumValue() string {
	if m != nil {
		return m.SumValue
	}
	return ""
}

type TokenBalance struct {
	TokenId              string   `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Total                string   `protobuf:"bytes,2,opt,name=total,proto3" json:"total,omitempty"`
	Active               string   `protobuf:"bytes,3,opt,name=active,proto3" json:"active,omitempty"`
	Locked               string   `protobuf:"bytes,4,opt,name=locked,proto3" json:"locked,omitempty"`
	Withdrawing          string   `protobuf:"bytes,5,opt,name=withdrawing,proto3" json:"withdrawing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenBalance) Reset()         { *m = TokenBalance{} }
func (m *TokenBalance) String() string { return proto.CompactTextString(m) }
func (*TokenBalance) ProtoMessage()    {}
func (*TokenBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{3}
}

func (m *TokenBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenBalance.Unmarshal(m, b)
}
func (m *TokenBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenBalance.Marshal(b, m, deterministic)
}
func (m *TokenBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenBalance.Merge(m, src)
}
func (m *TokenBalance) XXX_Size() int {
	return xxx_messageInfo_TokenBalance.Size(m)
}
func (m *TokenBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenBalance.DiscardUnknown(m)
}

var xxx_messageInfo_TokenBalance proto.InternalMessageInfo

func (m *TokenBalance) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *TokenBalance) GetTotal() string {
	if m != nil {
		return m.Total
	}
	return ""
}

func (m *TokenBalance) GetActive() string {
	if m != nil {
		return m.Active
	}
	return ""
}

func (m *TokenBalance) GetLocked() string {
	if m != nil {
		return m.Locked
	}
	return ""
}

func (m *TokenBalance) GetWithdrawing() string {
	if m != nil {
		return m.Withdrawing
	}
	return ""
}

type TradeRecord struct {
	PairId string `protobuf:"bytes,1,opt,name=pair_id,json=pairId,proto3" json:"pair_id,omitempty"`
	TimeMs int64  `protobuf:"varint,2,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	// From which trader's view is context dependent.
	Action dex2.Order_Action `protobuf:"varint,3,opt,name=action,proto3,enum=dex.Order_Action" json:"action,omitempty"`
	// The trade price.
	Price string `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	// The amount fulfilled of each side in this trade.
	Amount string `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	// Total value of the trade which is `price` * `amount`
	Value                string   `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeRecord) Reset()         { *m = TradeRecord{} }
func (m *TradeRecord) String() string { return proto.CompactTextString(m) }
func (*TradeRecord) ProtoMessage()    {}
func (*TradeRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{4}
}

func (m *TradeRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeRecord.Unmarshal(m, b)
}
func (m *TradeRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeRecord.Marshal(b, m, deterministic)
}
func (m *TradeRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeRecord.Merge(m, src)
}
func (m *TradeRecord) XXX_Size() int {
	return xxx_messageInfo_TradeRecord.Size(m)
}
func (m *TradeRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeRecord.DiscardUnknown(m)
}

var xxx_messageInfo_TradeRecord proto.InternalMessageInfo

func (m *TradeRecord) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *TradeRecord) GetTimeMs() int64 {
	if m != nil {
		return m.TimeMs
	}
	return 0
}

func (m *TradeRecord) GetAction() dex2.Order_Action {
	if m != nil {
		return m.Action
	}
	return dex2.Order_UnknownAction
}

func (m *TradeRecord) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *TradeRecord) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *TradeRecord) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MyTrade struct {
	PairId               string   `protobuf:"bytes,1,opt,name=pair_id,json=pairId,proto3" json:"pair_id,omitempty"`
	TimeMs               int64    `protobuf:"varint,2,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	OrderId              int64    `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	IsBuyer              bool     `protobuf:"varint,4,opt,name=is_buyer,json=isBuyer,proto3" json:"is_buyer,omitempty"`
	IsMaker              bool     `protobuf:"varint,5,opt,name=is_maker,json=isMaker,proto3" json:"is_maker,omitempty"`
	Price                string   `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Amount               string   `protobuf:"bytes,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee                  string   `protobuf:"bytes,8,opt,name=fee,proto3" json:"fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyTrade) Reset()         { *m = MyTrade{} }
func (m *MyTrade) String() string { return proto.CompactTextString(m) }
func (*MyTrade) ProtoMessage()    {}
func (*MyTrade) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{5}
}

func (m *MyTrade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyTrade.Unmarshal(m, b)
}
func (m *MyTrade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyTrade.Marshal(b, m, deterministic)
}
func (m *MyTrade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyTrade.Merge(m, src)
}
func (m *MyTrade) XXX_Size() int {
	return xxx_messageInfo_MyTrade.Size(m)
}
func (m *MyTrade) XXX_DiscardUnknown() {
	xxx_messageInfo_MyTrade.DiscardUnknown(m)
}

var xxx_messageInfo_MyTrade proto.InternalMessageInfo

func (m *MyTrade) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *MyTrade) GetTimeMs() int64 {
	if m != nil {
		return m.TimeMs
	}
	return 0
}

func (m *MyTrade) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *MyTrade) GetIsBuyer() bool {
	if m != nil {
		return m.IsBuyer
	}
	return false
}

func (m *MyTrade) GetIsMaker() bool {
	if m != nil {
		return m.IsMaker
	}
	return false
}

func (m *MyTrade) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *MyTrade) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *MyTrade) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

// Transfer
type Transfer struct {
	TimeMs int64           `protobuf:"varint,1,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	Action Transfer_Action `protobuf:"varint,2,opt,name=action,proto3,enum=dfe.Transfer_Action" json:"action,omitempty"`
	// The id of the transferred token.
	TokenId string `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// The amount transferred.
	Amount string `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// The balance (including locked part) after the transfer.
	Balance string `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance,omitempty"`
	// Deposit - "Confirming" | "Done"
	// Withdraw - "Confirming" | "Confirmed" | "Done"
	Status string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// The transaction hash of a deposit.
	DepositTx string `protobuf:"bytes,7,opt,name=deposit_tx,json=depositTx,proto3" json:"deposit_tx,omitempty"`
	// The block number of a deposit
	DepositBlockNumber   int64    `protobuf:"varint,8,opt,name=deposit_block_number,json=depositBlockNumber,proto3" json:"deposit_block_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transfer) Reset()         { *m = Transfer{} }
func (m *Transfer) String() string { return proto.CompactTextString(m) }
func (*Transfer) ProtoMessage()    {}
func (*Transfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{6}
}

func (m *Transfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transfer.Unmarshal(m, b)
}
func (m *Transfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transfer.Marshal(b, m, deterministic)
}
func (m *Transfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transfer.Merge(m, src)
}
func (m *Transfer) XXX_Size() int {
	return xxx_messageInfo_Transfer.Size(m)
}
func (m *Transfer) XXX_DiscardUnknown() {
	xxx_messageInfo_Transfer.DiscardUnknown(m)
}

var xxx_messageInfo_Transfer proto.InternalMessageInfo

func (m *Transfer) GetTimeMs() int64 {
	if m != nil {
		return m.TimeMs
	}
	return 0
}

func (m *Transfer) GetAction() Transfer_Action {
	if m != nil {
		return m.Action
	}
	return Transfer_UnknownAction
}

func (m *Transfer) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *Transfer) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Transfer) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *Transfer) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Transfer) GetDepositTx() string {
	if m != nil {
		return m.DepositTx
	}
	return ""
}

func (m *Transfer) GetDepositBlockNumber() int64 {
	if m != nil {
		return m.DepositBlockNumber
	}
	return 0
}

// TradingConfig
type TradingConfig struct {
	// Maximum open orders per trader.
	MaxOpenOrdersPerTrader int32 `protobuf:"varint,1,opt,name=max_open_orders_per_trader,json=maxOpenOrdersPerTrader,proto3" json:"max_open_orders_per_trader,omitempty"`
	// The minimum ttl for new orders.
	MinNewOrderTtlSec int64 `protobuf:"varint,2,opt,name=min_new_order_ttl_sec,json=minNewOrderTtlSec,proto3" json:"min_new_order_ttl_sec,omitempty"`
	// Keyed by token id, i.e. token symbol.
	Tokens               map[string]*TokenLimit `protobuf:"bytes,3,rep,name=tokens,proto3" json:"tokens,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TradingConfig) Reset()         { *m = TradingConfig{} }
func (m *TradingConfig) String() string { return proto.CompactTextString(m) }
func (*TradingConfig) ProtoMessage()    {}
func (*TradingConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{7}
}

func (m *TradingConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradingConfig.Unmarshal(m, b)
}
func (m *TradingConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradingConfig.Marshal(b, m, deterministic)
}
func (m *TradingConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradingConfig.Merge(m, src)
}
func (m *TradingConfig) XXX_Size() int {
	return xxx_messageInfo_TradingConfig.Size(m)
}
func (m *TradingConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TradingConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TradingConfig proto.InternalMessageInfo

func (m *TradingConfig) GetMaxOpenOrdersPerTrader() int32 {
	if m != nil {
		return m.MaxOpenOrdersPerTrader
	}
	return 0
}

func (m *TradingConfig) GetMinNewOrderTtlSec() int64 {
	if m != nil {
		return m.MinNewOrderTtlSec
	}
	return 0
}

func (m *TradingConfig) GetTokens() map[string]*TokenLimit {
	if m != nil {
		return m.Tokens
	}
	return nil
}

type TokenLimit struct {
	// The minimum amount of tokens for new order.
	MinPlaceOrderAmount float64 `protobuf:"fixed64,1,opt,name=min_place_order_amount,json=minPlaceOrderAmount,proto3" json:"min_place_order_amount,omitempty"`
	// The minimum value of new order. Set this value when a token is used as cash, e.g. ETH.
	MinPlaceOrderValue float64 `protobuf:"fixed64,2,opt,name=min_place_order_value,json=minPlaceOrderValue,proto3" json:"min_place_order_value,omitempty"`
	// The minimum deposit amount of token.
	MinDepositAmount float64 `protobuf:"fixed64,3,opt,name=min_deposit_amount,json=minDepositAmount,proto3" json:"min_deposit_amount,omitempty"`
	// The minimum amount of token withdrawals.
	MinWithdrawAmount   float64 `protobuf:"fixed64,4,opt,name=min_withdraw_amount,json=minWithdrawAmount,proto3" json:"min_withdraw_amount,omitempty"`
	TradingStartTimeSec int64   `protobuf:"varint,5,opt,name=trading_start_time_sec,json=tradingStartTimeSec,proto3" json:"trading_start_time_sec,omitempty"`
	// Token will be delisted (NO LONGER support deposit, withdrawal or trading) at this time.
	// Deposit and trading closes at `delist_time_sec` - 30days
	DelistTimeSec        int64    `protobuf:"varint,7,opt,name=delist_time_sec,json=delistTimeSec,proto3" json:"delist_time_sec,omitempty"`
	EnableTimeSec        int64    `protobuf:"varint,8,opt,name=enable_time_sec,json=enableTimeSec,proto3" json:"enable_time_sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenLimit) Reset()         { *m = TokenLimit{} }
func (m *TokenLimit) String() string { return proto.CompactTextString(m) }
func (*TokenLimit) ProtoMessage()    {}
func (*TokenLimit) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{8}
}

func (m *TokenLimit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenLimit.Unmarshal(m, b)
}
func (m *TokenLimit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenLimit.Marshal(b, m, deterministic)
}
func (m *TokenLimit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenLimit.Merge(m, src)
}
func (m *TokenLimit) XXX_Size() int {
	return xxx_messageInfo_TokenLimit.Size(m)
}
func (m *TokenLimit) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenLimit.DiscardUnknown(m)
}

var xxx_messageInfo_TokenLimit proto.InternalMessageInfo

func (m *TokenLimit) GetMinPlaceOrderAmount() float64 {
	if m != nil {
		return m.MinPlaceOrderAmount
	}
	return 0
}

func (m *TokenLimit) GetMinPlaceOrderValue() float64 {
	if m != nil {
		return m.MinPlaceOrderValue
	}
	return 0
}

func (m *TokenLimit) GetMinDepositAmount() float64 {
	if m != nil {
		return m.MinDepositAmount
	}
	return 0
}

func (m *TokenLimit) GetMinWithdrawAmount() float64 {
	if m != nil {
		return m.MinWithdrawAmount
	}
	return 0
}

func (m *TokenLimit) GetTradingStartTimeSec() int64 {
	if m != nil {
		return m.TradingStartTimeSec
	}
	return 0
}

func (m *TokenLimit) GetDelistTimeSec() int64 {
	if m != nil {
		return m.DelistTimeSec
	}
	return 0
}

func (m *TokenLimit) GetEnableTimeSec() int64 {
	if m != nil {
		return m.EnableTimeSec
	}
	return 0
}

type Order struct {
	OrderId              int64             `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PairId               string            `protobuf:"bytes,2,opt,name=pair_id,json=pairId,proto3" json:"pair_id,omitempty"`
	Action               dex2.Order_Action `protobuf:"varint,3,opt,name=action,proto3,enum=dex.Order_Action" json:"action,omitempty"`
	Price                string            `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	AmountTotal          string            `protobuf:"bytes,5,opt,name=amount_total,json=amountTotal,proto3" json:"amount_total,omitempty"`
	AmountFilled         string            `protobuf:"bytes,6,opt,name=amount_filled,json=amountFilled,proto3" json:"amount_filled,omitempty"`
	FilledAveragePrice   string            `protobuf:"bytes,7,opt,name=filled_average_price,json=filledAveragePrice,proto3" json:"filled_average_price,omitempty"`
	Status               dex2.Order_Status `protobuf:"varint,8,opt,name=status,proto3,enum=dex.Order_Status" json:"status,omitempty"`
	CreateTimeMs         int64             `protobuf:"varint,9,opt,name=create_time_ms,json=createTimeMs,proto3" json:"create_time_ms,omitempty"`
	UpdateTimeMs         int64             `protobuf:"varint,10,opt,name=update_time_ms,json=updateTimeMs,proto3" json:"update_time_ms,omitempty"`
	ExpireTimeSec        int64             `protobuf:"varint,11,opt,name=expire_time_sec,json=expireTimeSec,proto3" json:"expire_time_sec,omitempty"`
	Nonce                int64             `protobuf:"varint,15,opt,name=nonce,proto3" json:"nonce,omitempty"`
	BookId               int64             `protobuf:"varint,16,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{9}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *Order) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *Order) GetAction() dex2.Order_Action {
	if m != nil {
		return m.Action
	}
	return dex2.Order_UnknownAction
}

func (m *Order) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Order) GetAmountTotal() string {
	if m != nil {
		return m.AmountTotal
	}
	return ""
}

func (m *Order) GetAmountFilled() string {
	if m != nil {
		return m.AmountFilled
	}
	return ""
}

func (m *Order) GetFilledAveragePrice() string {
	if m != nil {
		return m.FilledAveragePrice
	}
	return ""
}

func (m *Order) GetStatus() dex2.Order_Status {
	if m != nil {
		return m.Status
	}
	return dex2.Order_UnknownStatus
}

func (m *Order) GetCreateTimeMs() int64 {
	if m != nil {
		return m.CreateTimeMs
	}
	return 0
}

func (m *Order) GetUpdateTimeMs() int64 {
	if m != nil {
		return m.UpdateTimeMs
	}
	return 0
}

func (m *Order) GetExpireTimeSec() int64 {
	if m != nil {
		return m.ExpireTimeSec
	}
	return 0
}

func (m *Order) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Order) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified        bool     `protobuf:"varint,4,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{10}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetEmailVerified() bool {
	if m != nil {
		return m.EmailVerified
	}
	return false
}

type AddrBinding struct {
	// Trader address, e.g. "0x1B38C16a23269Ef3D776A16B46b0f2f160Fcf7FC".
	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// The user id which `addr` is bound to.
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddrBinding) Reset()         { *m = AddrBinding{} }
func (m *AddrBinding) String() string { return proto.CompactTextString(m) }
func (*AddrBinding) ProtoMessage()    {}
func (*AddrBinding) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{11}
}

func (m *AddrBinding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddrBinding.Unmarshal(m, b)
}
func (m *AddrBinding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddrBinding.Marshal(b, m, deterministic)
}
func (m *AddrBinding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddrBinding.Merge(m, src)
}
func (m *AddrBinding) XXX_Size() int {
	return xxx_messageInfo_AddrBinding.Size(m)
}
func (m *AddrBinding) XXX_DiscardUnknown() {
	xxx_messageInfo_AddrBinding.DiscardUnknown(m)
}

var xxx_messageInfo_AddrBinding proto.InternalMessageInfo

func (m *AddrBinding) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *AddrBinding) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

// A rate limit that at most `num` occurrences within `windowSec`.
type RateLimit struct {
	WindowSec            int64    `protobuf:"varint,1,opt,name=windowSec,proto3" json:"windowSec,omitempty"`
	Num                  int64    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RateLimit) Reset()         { *m = RateLimit{} }
func (m *RateLimit) String() string { return proto.CompactTextString(m) }
func (*RateLimit) ProtoMessage()    {}
func (*RateLimit) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{12}
}

func (m *RateLimit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateLimit.Unmarshal(m, b)
}
func (m *RateLimit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateLimit.Marshal(b, m, deterministic)
}
func (m *RateLimit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateLimit.Merge(m, src)
}
func (m *RateLimit) XXX_Size() int {
	return xxx_messageInfo_RateLimit.Size(m)
}
func (m *RateLimit) XXX_DiscardUnknown() {
	xxx_messageInfo_RateLimit.DiscardUnknown(m)
}

var xxx_messageInfo_RateLimit proto.InternalMessageInfo

func (m *RateLimit) GetWindowSec() int64 {
	if m != nil {
		return m.WindowSec
	}
	return 0
}

func (m *RateLimit) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type BannerConfig struct {
	Campaigns            []*Campaign `protobuf:"bytes,1,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BannerConfig) Reset()         { *m = BannerConfig{} }
func (m *BannerConfig) String() string { return proto.CompactTextString(m) }
func (*BannerConfig) ProtoMessage()    {}
func (*BannerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{13}
}

func (m *BannerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BannerConfig.Unmarshal(m, b)
}
func (m *BannerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BannerConfig.Marshal(b, m, deterministic)
}
func (m *BannerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BannerConfig.Merge(m, src)
}
func (m *BannerConfig) XXX_Size() int {
	return xxx_messageInfo_BannerConfig.Size(m)
}
func (m *BannerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BannerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BannerConfig proto.InternalMessageInfo

func (m *BannerConfig) GetCampaigns() []*Campaign {
	if m != nil {
		return m.Campaigns
	}
	return nil
}

type Campaign struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Lang                 string   `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	ImageUrl             string   `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	ThumbnailUrl         string   `protobuf:"bytes,4,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	ArticleUrl           string   `protobuf:"bytes,5,opt,name=article_url,json=articleUrl,proto3" json:"article_url,omitempty"`
	BgColor              string   `protobuf:"bytes,6,opt,name=bg_color,json=bgColor,proto3" json:"bg_color,omitempty"`
	OrderNum             int32    `protobuf:"varint,7,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`
	StartTimeSec         int64    `protobuf:"varint,8,opt,name=start_time_sec,json=startTimeSec,proto3" json:"start_time_sec,omitempty"`
	EndTimeSec           int64    `protobuf:"varint,9,opt,name=end_time_sec,json=endTimeSec,proto3" json:"end_time_sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Campaign) Reset()         { *m = Campaign{} }
func (m *Campaign) String() string { return proto.CompactTextString(m) }
func (*Campaign) ProtoMessage()    {}
func (*Campaign) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{14}
}

func (m *Campaign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Campaign.Unmarshal(m, b)
}
func (m *Campaign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Campaign.Marshal(b, m, deterministic)
}
func (m *Campaign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Campaign.Merge(m, src)
}
func (m *Campaign) XXX_Size() int {
	return xxx_messageInfo_Campaign.Size(m)
}
func (m *Campaign) XXX_DiscardUnknown() {
	xxx_messageInfo_Campaign.DiscardUnknown(m)
}

var xxx_messageInfo_Campaign proto.InternalMessageInfo

func (m *Campaign) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Campaign) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *Campaign) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *Campaign) GetThumbnailUrl() string {
	if m != nil {
		return m.ThumbnailUrl
	}
	return ""
}

func (m *Campaign) GetArticleUrl() string {
	if m != nil {
		return m.ArticleUrl
	}
	return ""
}

func (m *Campaign) GetBgColor() string {
	if m != nil {
		return m.BgColor
	}
	return ""
}

func (m *Campaign) GetOrderNum() int32 {
	if m != nil {
		return m.OrderNum
	}
	return 0
}

func (m *Campaign) GetStartTimeSec() int64 {
	if m != nil {
		return m.StartTimeSec
	}
	return 0
}

func (m *Campaign) GetEndTimeSec() int64 {
	if m != nil {
		return m.EndTimeSec
	}
	return 0
}

type MarketConfig struct {
	MakerFeeRateE4    uint64 `protobuf:"varint,1,opt,name=maker_fee_rate_e4,json=makerFeeRateE4,proto3" json:"maker_fee_rate_e4,omitempty"`
	TakerFeeRateE4    uint64 `protobuf:"varint,2,opt,name=taker_fee_rate_e4,json=takerFeeRateE4,proto3" json:"taker_fee_rate_e4,omitempty"`
	WithdrawFeeRateE4 uint64 `protobuf:"varint,3,opt,name=withdraw_fee_rate_e4,json=withdrawFeeRateE4,proto3" json:"withdraw_fee_rate_e4,omitempty"`
	// The tokens that are can be used as cash in this market.
	CashTokens []*TokenInfo `protobuf:"bytes,5,rep,name=cash_tokens,json=cashTokens,proto3" json:"cash_tokens,omitempty"`
	// The tokens that can be traded as stock in this market.
	StockTokens          []*TokenInfo `protobuf:"bytes,6,rep,name=stock_tokens,json=stockTokens,proto3" json:"stock_tokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MarketConfig) Reset()         { *m = MarketConfig{} }
func (m *MarketConfig) String() string { return proto.CompactTextString(m) }
func (*MarketConfig) ProtoMessage()    {}
func (*MarketConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{15}
}

func (m *MarketConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketConfig.Unmarshal(m, b)
}
func (m *MarketConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketConfig.Marshal(b, m, deterministic)
}
func (m *MarketConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketConfig.Merge(m, src)
}
func (m *MarketConfig) XXX_Size() int {
	return xxx_messageInfo_MarketConfig.Size(m)
}
func (m *MarketConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketConfig.DiscardUnknown(m)
}

var xxx_messageInfo_MarketConfig proto.InternalMessageInfo

func (m *MarketConfig) GetMakerFeeRateE4() uint64 {
	if m != nil {
		return m.MakerFeeRateE4
	}
	return 0
}

func (m *MarketConfig) GetTakerFeeRateE4() uint64 {
	if m != nil {
		return m.TakerFeeRateE4
	}
	return 0
}

func (m *MarketConfig) GetWithdrawFeeRateE4() uint64 {
	if m != nil {
		return m.WithdrawFeeRateE4
	}
	return 0
}

func (m *MarketConfig) GetCashTokens() []*TokenInfo {
	if m != nil {
		return m.CashTokens
	}
	return nil
}

func (m *MarketConfig) GetStockTokens() []*TokenInfo {
	if m != nil {
		return m.StockTokens
	}
	return nil
}

type TokenInfo struct {
	TokenId              string   `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	TokenName            string   `protobuf:"bytes,2,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	TokenCode            uint32   `protobuf:"varint,3,opt,name=token_code,json=tokenCode,proto3" json:"token_code,omitempty"`
	TokenAddr            string   `protobuf:"bytes,4,opt,name=token_addr,json=tokenAddr,proto3" json:"token_addr,omitempty"`
	ScaleFactor          uint64   `protobuf:"varint,5,opt,name=scale_factor,json=scaleFactor,proto3" json:"scale_factor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenInfo) Reset()         { *m = TokenInfo{} }
func (m *TokenInfo) String() string { return proto.CompactTextString(m) }
func (*TokenInfo) ProtoMessage()    {}
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{16}
}

func (m *TokenInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenInfo.Unmarshal(m, b)
}
func (m *TokenInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenInfo.Marshal(b, m, deterministic)
}
func (m *TokenInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenInfo.Merge(m, src)
}
func (m *TokenInfo) XXX_Size() int {
	return xxx_messageInfo_TokenInfo.Size(m)
}
func (m *TokenInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TokenInfo proto.InternalMessageInfo

func (m *TokenInfo) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *TokenInfo) GetTokenName() string {
	if m != nil {
		return m.TokenName
	}
	return ""
}

func (m *TokenInfo) GetTokenCode() uint32 {
	if m != nil {
		return m.TokenCode
	}
	return 0
}

func (m *TokenInfo) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

func (m *TokenInfo) GetScaleFactor() uint64 {
	if m != nil {
		return m.ScaleFactor
	}
	return 0
}

type TokenMetadata struct {
	TokenId              string                     `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	TokenName            string                     `protobuf:"bytes,2,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	TokenAddr            string                     `protobuf:"bytes,3,opt,name=token_addr,json=tokenAddr,proto3" json:"token_addr,omitempty"`
	Tags                 []string                   `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Description          *TokenMetadata_Description `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	InitPrice            string                     `protobuf:"bytes,6,opt,name=init_price,json=initPrice,proto3" json:"init_price,omitempty"`
	TotalAmount          string                     `protobuf:"bytes,7,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Circulation          string                     `protobuf:"bytes,8,opt,name=circulation,proto3" json:"circulation,omitempty"`
	GasLimit             string                     `protobuf:"bytes,9,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	TokenLogo            string                     `protobuf:"bytes,10,opt,name=token_logo,json=tokenLogo,proto3" json:"token_logo,omitempty"`
	Website              string                     `protobuf:"bytes,11,opt,name=website,proto3" json:"website,omitempty"`
	Reporters            []*TokenMetadata_Reporter  `protobuf:"bytes,12,rep,name=reporters,proto3" json:"reporters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *TokenMetadata) Reset()         { *m = TokenMetadata{} }
func (m *TokenMetadata) String() string { return proto.CompactTextString(m) }
func (*TokenMetadata) ProtoMessage()    {}
func (*TokenMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{17}
}

func (m *TokenMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenMetadata.Unmarshal(m, b)
}
func (m *TokenMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenMetadata.Marshal(b, m, deterministic)
}
func (m *TokenMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenMetadata.Merge(m, src)
}
func (m *TokenMetadata) XXX_Size() int {
	return xxx_messageInfo_TokenMetadata.Size(m)
}
func (m *TokenMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_TokenMetadata proto.InternalMessageInfo

func (m *TokenMetadata) GetTokenId() string {
	if m != nil {
		return m.TokenId
	}
	return ""
}

func (m *TokenMetadata) GetTokenName() string {
	if m != nil {
		return m.TokenName
	}
	return ""
}

func (m *TokenMetadata) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

func (m *TokenMetadata) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *TokenMetadata) GetDescription() *TokenMetadata_Description {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *TokenMetadata) GetInitPrice() string {
	if m != nil {
		return m.InitPrice
	}
	return ""
}

func (m *TokenMetadata) GetTotalAmount() string {
	if m != nil {
		return m.TotalAmount
	}
	return ""
}

func (m *TokenMetadata) GetCirculation() string {
	if m != nil {
		return m.Circulation
	}
	return ""
}

func (m *TokenMetadata) GetGasLimit() string {
	if m != nil {
		return m.GasLimit
	}
	return ""
}

func (m *TokenMetadata) GetTokenLogo() string {
	if m != nil {
		return m.TokenLogo
	}
	return ""
}

func (m *TokenMetadata) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *TokenMetadata) GetReporters() []*TokenMetadata_Reporter {
	if m != nil {
		return m.Reporters
	}
	return nil
}

type TokenMetadata_Description struct {
	En                   string   `protobuf:"bytes,1,opt,name=en,proto3" json:"en,omitempty"`
	Zh                   string   `protobuf:"bytes,2,opt,name=zh,proto3" json:"zh,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenMetadata_Description) Reset()         { *m = TokenMetadata_Description{} }
func (m *TokenMetadata_Description) String() string { return proto.CompactTextString(m) }
func (*TokenMetadata_Description) ProtoMessage()    {}
func (*TokenMetadata_Description) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{17, 0}
}

func (m *TokenMetadata_Description) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenMetadata_Description.Unmarshal(m, b)
}
func (m *TokenMetadata_Description) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenMetadata_Description.Marshal(b, m, deterministic)
}
func (m *TokenMetadata_Description) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenMetadata_Description.Merge(m, src)
}
func (m *TokenMetadata_Description) XXX_Size() int {
	return xxx_messageInfo_TokenMetadata_Description.Size(m)
}
func (m *TokenMetadata_Description) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenMetadata_Description.DiscardUnknown(m)
}

var xxx_messageInfo_TokenMetadata_Description proto.InternalMessageInfo

func (m *TokenMetadata_Description) GetEn() string {
	if m != nil {
		return m.En
	}
	return ""
}

func (m *TokenMetadata_Description) GetZh() string {
	if m != nil {
		return m.Zh
	}
	return ""
}

type TokenMetadata_Reporter struct {
	Report               string   `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	Reporter             string   `protobuf:"bytes,2,opt,name=reporter,proto3" json:"reporter,omitempty"`
	ReporterSite         string   `protobuf:"bytes,3,opt,name=reporter_site,json=reporterSite,proto3" json:"reporter_site,omitempty"`
	ReporterLogo         string   `protobuf:"bytes,4,opt,name=reporter_logo,json=reporterLogo,proto3" json:"reporter_logo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenMetadata_Reporter) Reset()         { *m = TokenMetadata_Reporter{} }
func (m *TokenMetadata_Reporter) String() string { return proto.CompactTextString(m) }
func (*TokenMetadata_Reporter) ProtoMessage()    {}
func (*TokenMetadata_Reporter) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{17, 1}
}

func (m *TokenMetadata_Reporter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenMetadata_Reporter.Unmarshal(m, b)
}
func (m *TokenMetadata_Reporter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenMetadata_Reporter.Marshal(b, m, deterministic)
}
func (m *TokenMetadata_Reporter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenMetadata_Reporter.Merge(m, src)
}
func (m *TokenMetadata_Reporter) XXX_Size() int {
	return xxx_messageInfo_TokenMetadata_Reporter.Size(m)
}
func (m *TokenMetadata_Reporter) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenMetadata_Reporter.DiscardUnknown(m)
}

var xxx_messageInfo_TokenMetadata_Reporter proto.InternalMessageInfo

func (m *TokenMetadata_Reporter) GetReport() string {
	if m != nil {
		return m.Report
	}
	return ""
}

func (m *TokenMetadata_Reporter) GetReporter() string {
	if m != nil {
		return m.Reporter
	}
	return ""
}

func (m *TokenMetadata_Reporter) GetReporterSite() string {
	if m != nil {
		return m.ReporterSite
	}
	return ""
}

func (m *TokenMetadata_Reporter) GetReporterLogo() string {
	if m != nil {
		return m.ReporterLogo
	}
	return ""
}

type NotificationConfig struct {
	Notifications        []*Notification `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NotificationConfig) Reset()         { *m = NotificationConfig{} }
func (m *NotificationConfig) String() string { return proto.CompactTextString(m) }
func (*NotificationConfig) ProtoMessage()    {}
func (*NotificationConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{18}
}

func (m *NotificationConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationConfig.Unmarshal(m, b)
}
func (m *NotificationConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationConfig.Marshal(b, m, deterministic)
}
func (m *NotificationConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationConfig.Merge(m, src)
}
func (m *NotificationConfig) XXX_Size() int {
	return xxx_messageInfo_NotificationConfig.Size(m)
}
func (m *NotificationConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationConfig.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationConfig proto.InternalMessageInfo

func (m *NotificationConfig) GetNotifications() []*Notification {
	if m != nil {
		return m.Notifications
	}
	return nil
}

type Notification struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Lang                 string   `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	ArticleUrl           string   `protobuf:"bytes,3,opt,name=article_url,json=articleUrl,proto3" json:"article_url,omitempty"`
	OrderNum             int32    `protobuf:"varint,4,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`
	StartTimeSec         int64    `protobuf:"varint,5,opt,name=start_time_sec,json=startTimeSec,proto3" json:"start_time_sec,omitempty"`
	EndTimeSec           int64    `protobuf:"varint,6,opt,name=end_time_sec,json=endTimeSec,proto3" json:"end_time_sec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{19}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Notification) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *Notification) GetArticleUrl() string {
	if m != nil {
		return m.ArticleUrl
	}
	return ""
}

func (m *Notification) GetOrderNum() int32 {
	if m != nil {
		return m.OrderNum
	}
	return 0
}

func (m *Notification) GetStartTimeSec() int64 {
	if m != nil {
		return m.StartTimeSec
	}
	return 0
}

func (m *Notification) GetEndTimeSec() int64 {
	if m != nil {
		return m.EndTimeSec
	}
	return 0
}

// SimpleWallet钱包回调信息。
type SimpleWalletCallBack struct {
	Protocol             string   `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Blockchain           string   `protobuf:"bytes,3,opt,name=blockchain,proto3" json:"blockchain,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sign                 string   `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
	UuID                 string   `protobuf:"bytes,6,opt,name=uuID,proto3" json:"uuID,omitempty"`
	Account              string   `protobuf:"bytes,7,opt,name=account,proto3" json:"account,omitempty"`
	Ref                  string   `protobuf:"bytes,8,opt,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleWalletCallBack) Reset()         { *m = SimpleWalletCallBack{} }
func (m *SimpleWalletCallBack) String() string { return proto.CompactTextString(m) }
func (*SimpleWalletCallBack) ProtoMessage()    {}
func (*SimpleWalletCallBack) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{20}
}

func (m *SimpleWalletCallBack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleWalletCallBack.Unmarshal(m, b)
}
func (m *SimpleWalletCallBack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleWalletCallBack.Marshal(b, m, deterministic)
}
func (m *SimpleWalletCallBack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleWalletCallBack.Merge(m, src)
}
func (m *SimpleWalletCallBack) XXX_Size() int {
	return xxx_messageInfo_SimpleWalletCallBack.Size(m)
}
func (m *SimpleWalletCallBack) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleWalletCallBack.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleWalletCallBack proto.InternalMessageInfo

func (m *SimpleWalletCallBack) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *SimpleWalletCallBack) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SimpleWalletCallBack) GetBlockchain() string {
	if m != nil {
		return m.Blockchain
	}
	return ""
}

func (m *SimpleWalletCallBack) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *SimpleWalletCallBack) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *SimpleWalletCallBack) GetUuID() string {
	if m != nil {
		return m.UuID
	}
	return ""
}

func (m *SimpleWalletCallBack) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SimpleWalletCallBack) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

// simple_wallet_record表中的记录。
type SimpleWalletRecord struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Action               int32    `protobuf:"varint,3,opt,name=action,proto3" json:"action,omitempty"`
	Status               int32    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Data                 string   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	CreateTime           int64    `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ExpireTime           int64    `protobuf:"varint,7,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleWalletRecord) Reset()         { *m = SimpleWalletRecord{} }
func (m *SimpleWalletRecord) String() string { return proto.CompactTextString(m) }
func (*SimpleWalletRecord) ProtoMessage()    {}
func (*SimpleWalletRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{21}
}

func (m *SimpleWalletRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleWalletRecord.Unmarshal(m, b)
}
func (m *SimpleWalletRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleWalletRecord.Marshal(b, m, deterministic)
}
func (m *SimpleWalletRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleWalletRecord.Merge(m, src)
}
func (m *SimpleWalletRecord) XXX_Size() int {
	return xxx_messageInfo_SimpleWalletRecord.Size(m)
}
func (m *SimpleWalletRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleWalletRecord.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleWalletRecord proto.InternalMessageInfo

func (m *SimpleWalletRecord) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SimpleWalletRecord) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *SimpleWalletRecord) GetAction() int32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *SimpleWalletRecord) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SimpleWalletRecord) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *SimpleWalletRecord) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *SimpleWalletRecord) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

type AppInfo struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	VersionUrl           string   `protobuf:"bytes,2,opt,name=version_url,json=versionUrl,proto3" json:"version_url,omitempty"`
	DownloadUrl          string   `protobuf:"bytes,3,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	Status               int64    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Comment              string   `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	CommentEn            string   `protobuf:"bytes,7,opt,name=comment_en,json=commentEn,proto3" json:"comment_en,omitempty"`
	Platform             string   `protobuf:"bytes,8,opt,name=platform,proto3" json:"platform,omitempty"`
	CreateTime           string   `protobuf:"bytes,9,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppInfo) Reset()         { *m = AppInfo{} }
func (m *AppInfo) String() string { return proto.CompactTextString(m) }
func (*AppInfo) ProtoMessage()    {}
func (*AppInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2718449e8e69b06, []int{22}
}

func (m *AppInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppInfo.Unmarshal(m, b)
}
func (m *AppInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppInfo.Marshal(b, m, deterministic)
}
func (m *AppInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppInfo.Merge(m, src)
}
func (m *AppInfo) XXX_Size() int {
	return xxx_messageInfo_AppInfo.Size(m)
}
func (m *AppInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AppInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AppInfo proto.InternalMessageInfo

func (m *AppInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *AppInfo) GetVersionUrl() string {
	if m != nil {
		return m.VersionUrl
	}
	return ""
}

func (m *AppInfo) GetDownloadUrl() string {
	if m != nil {
		return m.DownloadUrl
	}
	return ""
}

func (m *AppInfo) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AppInfo) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *AppInfo) GetCommentEn() string {
	if m != nil {
		return m.CommentEn
	}
	return ""
}

func (m *AppInfo) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *AppInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func init() {
	proto.RegisterEnum("dfe.Transfer_Action", Transfer_Action_name, Transfer_Action_value)
	proto.RegisterType((*PairInfo)(nil), "dfe.PairInfo")
	proto.RegisterType((*Depth)(nil), "dfe.Depth")
	proto.RegisterType((*DepthEntry)(nil), "dfe.DepthEntry")
	proto.RegisterType((*TokenBalance)(nil), "dfe.TokenBalance")
	proto.RegisterType((*TradeRecord)(nil), "dfe.TradeRecord")
	proto.RegisterType((*MyTrade)(nil), "dfe.MyTrade")
	proto.RegisterType((*Transfer)(nil), "dfe.Transfer")
	proto.RegisterType((*TradingConfig)(nil), "dfe.TradingConfig")
	proto.RegisterMapType((map[string]*TokenLimit)(nil), "dfe.TradingConfig.TokensEntry")
	proto.RegisterType((*TokenLimit)(nil), "dfe.TokenLimit")
	proto.RegisterType((*Order)(nil), "dfe.Order")
	proto.RegisterType((*User)(nil), "dfe.User")
	proto.RegisterType((*AddrBinding)(nil), "dfe.AddrBinding")
	proto.RegisterType((*RateLimit)(nil), "dfe.RateLimit")
	proto.RegisterType((*BannerConfig)(nil), "dfe.BannerConfig")
	proto.RegisterType((*Campaign)(nil), "dfe.Campaign")
	proto.RegisterType((*MarketConfig)(nil), "dfe.MarketConfig")
	proto.RegisterType((*TokenInfo)(nil), "dfe.TokenInfo")
	proto.RegisterType((*TokenMetadata)(nil), "dfe.TokenMetadata")
	proto.RegisterType((*TokenMetadata_Description)(nil), "dfe.TokenMetadata.Description")
	proto.RegisterType((*TokenMetadata_Reporter)(nil), "dfe.TokenMetadata.Reporter")
	proto.RegisterType((*NotificationConfig)(nil), "dfe.NotificationConfig")
	proto.RegisterType((*Notification)(nil), "dfe.Notification")
	proto.RegisterType((*SimpleWalletCallBack)(nil), "dfe.SimpleWalletCallBack")
	proto.RegisterType((*SimpleWalletRecord)(nil), "dfe.SimpleWalletRecord")
	proto.RegisterType((*AppInfo)(nil), "dfe.AppInfo")
}

func init() { proto.RegisterFile("dfedata.proto", fileDescriptor_c2718449e8e69b06) }

var fileDescriptor_c2718449e8e69b06 = []byte{
	// 2109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x4f, 0x73, 0x1c, 0x47,
	0x15, 0x67, 0xf6, 0xff, 0xbe, 0xdd, 0x95, 0xa5, 0x89, 0x62, 0x64, 0x85, 0xd8, 0xca, 0x24, 0xa1,
	0x6c, 0x30, 0xeb, 0x44, 0x56, 0x05, 0x48, 0x38, 0x60, 0xf9, 0x4f, 0x95, 0xa8, 0xc8, 0x51, 0x8d,
	0xe4, 0xa4, 0x8a, 0xcb, 0x54, 0xef, 0x4c, 0xef, 0x6e, 0x97, 0x66, 0xba, 0xa7, 0x7a, 0x7a, 0xb5,
	0x52, 0x6e, 0x14, 0x17, 0xae, 0x1c, 0xf8, 0x0a, 0xdc, 0xe0, 0x23, 0xc0, 0x85, 0x23, 0x77, 0x6e,
	0x7c, 0x03, 0x6e, 0x5c, 0xb8, 0x51, 0xef, 0x75, 0xcf, 0xce, 0xac, 0x2c, 0x20, 0x65, 0x72, 0xeb,
	0xf7, 0x7b, 0xaf, 0xa7, 0xdf, 0xbf, 0xfe, 0x75, 0xf7, 0xc0, 0x28, 0x99, 0xf2, 0x84, 0x19, 0x36,
	0xce, 0xb5, 0x32, 0xca, 0x6f, 0x26, 0x53, 0xbe, 0xfb, 0xb3, 0x99, 0x30, 0xe3, 0x89, 0x98, 0xa8,
	0xcb, 0x71, 0xac, 0xb2, 0x47, 0x09, 0xbf, 0x34, 0x2a, 0x7f, 0x14, 0xab, 0x2c, 0x53, 0x72, 0x3c,
	0x13, 0xe6, 0x11, 0xd9, 0x22, 0xbe, 0xff, 0x28, 0xe5, 0xc9, 0x8c, 0xeb, 0xc2, 0x30, 0xc3, 0xed,
	0x27, 0x82, 0x3f, 0x34, 0xa0, 0x77, 0xc2, 0x84, 0x3e, 0x92, 0x53, 0xe5, 0x7f, 0x17, 0xba, 0x39,
	0x13, 0x3a, 0x12, 0xc9, 0x8e, 0xb7, 0xe7, 0xdd, 0xef, 0x87, 0x1d, 0x14, 0x8f, 0x12, 0x54, 0x18,
	0x91, 0xf1, 0x28, 0x2b, 0x76, 0x1a, 0x7b, 0xde, 0xfd, 0x66, 0xd8, 0x41, 0xf1, 0xb8, 0xf0, 0xdf,
	0x05, 0x50, 0x39, 0x97, 0x51, 0xae, 0x45, 0xcc, 0x77, 0x9a, 0x34, 0xa9, 0x8f, 0xc8, 0x09, 0x02,
	0xa8, 0x4e, 0x59, 0x61, 0x9c, 0xba, 0x65, 0xd5, 0x88, 0x58, 0xf5, 0x3b, 0xd0, 0xbf, 0x50, 0xe9,
	0x22, 0xe3, 0xd1, 0xfe, 0xc1, 0x4e, 0x9b, 0xb4, 0x3d, 0x0b, 0xec, 0x1f, 0xa0, 0x92, 0x65, 0x6a,
	0x21, 0x0d, 0x2a, 0x3b, 0x56, 0x69, 0x01, 0xab, 0x8c, 0xe7, 0x4c, 0xce, 0x68, 0x66, 0xd7, 0x2a,
	0x2d, 0xb0, 0x7f, 0xe0, 0xff, 0x00, 0xb6, 0x9c, 0x32, 0xe7, 0x3a, 0xe6, 0xf6, 0x0b, 0x3d, 0x32,
	0xba, 0x65, 0x15, 0x27, 0x16, 0xdf, 0x3f, 0xc0, 0xc8, 0xe6, 0x62, 0x36, 0x47, 0x8b, 0xbe, 0x0d,
	0x19, 0xc5, 0xfd, 0x03, 0xff, 0x6d, 0xe8, 0xa4, 0x6a, 0x89, 0x38, 0x10, 0xde, 0x4e, 0xd5, 0x72,
	0xff, 0x20, 0xf8, 0xb5, 0x07, 0xed, 0x67, 0x3c, 0x37, 0xf3, 0x37, 0x48, 0xd6, 0xfb, 0xd0, 0x62,
	0xc5, 0x79, 0xb1, 0xd3, 0xdc, 0x6b, 0xde, 0x1f, 0xec, 0xdf, 0x1a, 0x27, 0x53, 0x3e, 0xa6, 0x6f,
	0x3d, 0x97, 0x46, 0x5f, 0x85, 0xa4, 0x44, 0xa3, 0x89, 0x48, 0x8a, 0x9d, 0xd6, 0x7f, 0x30, 0x42,
	0x65, 0x70, 0x09, 0x50, 0x61, 0xfe, 0x36, 0xb4, 0x6d, 0x82, 0xad, 0x1f, 0x56, 0xf0, 0x6f, 0x43,
	0xc7, 0xa6, 0x8b, 0xbc, 0xe8, 0x87, 0x4e, 0xf2, 0xef, 0xc1, 0xc0, 0x28, 0xc3, 0xd2, 0xe8, 0x82,
	0xa5, 0x8b, 0xb2, 0x66, 0x40, 0xd0, 0x97, 0x88, 0x60, 0x6e, 0x8b, 0x45, 0xe6, 0xd4, 0xb6, 0x66,
	0xbd, 0x62, 0x91, 0x91, 0x32, 0xf8, 0xad, 0x07, 0xc3, 0x33, 0x75, 0xce, 0xe5, 0x21, 0x4b, 0x99,
	0x8c, 0xb9, 0x7f, 0x07, 0x7a, 0x06, 0xe5, 0x2a, 0x0f, 0x5d, 0x92, 0x8f, 0x12, 0xf4, 0x8b, 0x3e,
	0xeb, 0x1c, 0xb0, 0x02, 0xf9, 0x15, 0x1b, 0x71, 0x51, 0x2e, 0xed, 0x24, 0xc4, 0x53, 0x15, 0x9f,
	0xf3, 0xc4, 0xad, 0xe9, 0x24, 0x7f, 0x0f, 0x06, 0x4b, 0x61, 0xe6, 0x89, 0x66, 0x4b, 0x21, 0x67,
	0xae, 0x4d, 0xea, 0x50, 0xf0, 0x47, 0x0f, 0x06, 0x67, 0x9a, 0x25, 0x3c, 0xe4, 0xb1, 0xd2, 0xc9,
	0x1b, 0x54, 0xe6, 0x81, 0xf5, 0x49, 0x49, 0xf2, 0x69, 0x63, 0x7f, 0x6b, 0x9c, 0xf0, 0xcb, 0xf1,
	0x17, 0x3a, 0xe1, 0x7a, 0xfc, 0x84, 0x14, 0xa1, 0x33, 0xa8, 0x92, 0xdd, 0xba, 0x39, 0xd9, 0xed,
	0xb5, 0x64, 0x6f, 0x43, 0xdb, 0xe6, 0xd1, 0x36, 0xb0, 0x15, 0x82, 0xbf, 0x7a, 0xd0, 0x3d, 0xbe,
	0x22, 0x97, 0xdf, 0xc0, 0xd9, 0x3b, 0xd0, 0x53, 0xe8, 0x19, 0x4e, 0x69, 0x92, 0xa6, 0x4b, 0xf2,
	0x51, 0x82, 0x2a, 0x51, 0x44, 0x93, 0xc5, 0x15, 0xd7, 0xe4, 0x5f, 0x2f, 0xec, 0x8a, 0xe2, 0x10,
	0x45, 0xa7, 0xca, 0xd8, 0x39, 0xd7, 0xe4, 0x23, 0xa9, 0x8e, 0x51, 0xac, 0x42, 0xea, 0xdc, 0x1c,
	0x52, 0x77, 0x2d, 0xa4, 0x4d, 0x68, 0x4e, 0x39, 0x77, 0xfb, 0x09, 0x87, 0xc1, 0x9f, 0x1b, 0xd0,
	0x3b, 0xd3, 0x4c, 0x16, 0x53, 0xae, 0xeb, 0x6e, 0x7b, 0x6b, 0x6e, 0x3f, 0x5c, 0xe5, 0xb8, 0x41,
	0x39, 0xde, 0xa6, 0xd6, 0x2e, 0xe7, 0x5d, 0x4f, 0x73, 0xbd, 0xad, 0x9a, 0xeb, 0x6d, 0x55, 0x39,
	0xd6, 0x5a, 0x73, 0x6c, 0x07, 0xba, 0x13, 0xdb, 0x94, 0xae, 0x08, 0xa5, 0x88, 0x33, 0x90, 0xf3,
	0x16, 0x85, 0x8b, 0xd0, 0x49, 0x48, 0x4f, 0x09, 0xcf, 0x55, 0x21, 0x4c, 0x64, 0x2e, 0x5d, 0x98,
	0x7d, 0x87, 0x9c, 0x5d, 0xfa, 0x1f, 0xc1, 0x76, 0xa9, 0x9e, 0x60, 0x33, 0x46, 0x72, 0x91, 0x4d,
	0xb8, 0xa6, 0xd0, 0x9b, 0xa1, 0xef, 0x74, 0x87, 0xa8, 0x7a, 0x49, 0x9a, 0xe0, 0x13, 0xe8, 0xd8,
	0x38, 0xfc, 0x2d, 0x18, 0xbd, 0x92, 0xe7, 0x52, 0x2d, 0xa5, 0x05, 0x36, 0xbf, 0xe3, 0x0f, 0xa0,
	0xfb, 0xcc, 0x4e, 0xd9, 0xf4, 0xfc, 0x21, 0xf4, 0xbe, 0x72, 0x2d, 0xbc, 0xd9, 0x08, 0x7e, 0xd5,
	0x80, 0x11, 0xb6, 0x83, 0x90, 0xb3, 0xa7, 0x4a, 0x4e, 0xc5, 0xcc, 0xff, 0x14, 0x76, 0x33, 0x76,
	0x19, 0x11, 0xb9, 0x52, 0x75, 0x0b, 0x24, 0xb3, 0xc8, 0x60, 0xcf, 0x68, 0xca, 0x6c, 0x3b, 0xbc,
	0x9d, 0xb1, 0xcb, 0x2f, 0x72, 0x2e, 0xa9, 0x4f, 0x8b, 0x13, 0xae, 0xa9, 0xa3, 0xb4, 0xff, 0x11,
	0xbc, 0x9d, 0x09, 0x19, 0x49, 0xbe, 0xb4, 0x53, 0x23, 0x63, 0xd2, 0xa8, 0xe0, 0xb1, 0xeb, 0xa3,
	0xad, 0x4c, 0xc8, 0x97, 0x7c, 0x49, 0xb3, 0xce, 0x4c, 0x7a, 0xca, 0x63, 0xff, 0x13, 0xe8, 0x50,
	0x76, 0x4b, 0x6e, 0xba, 0x5b, 0xd6, 0xa6, 0xf2, 0x68, 0x4c, 0xbb, 0xbe, 0xb0, 0x2c, 0xe4, 0xac,
	0x77, 0x7f, 0x01, 0x83, 0x1a, 0x8c, 0xad, 0x71, 0xce, 0xaf, 0x5c, 0x1f, 0xe3, 0xd0, 0xff, 0xb0,
	0xec, 0x7f, 0x5c, 0xba, 0xa4, 0x33, 0x9a, 0xf2, 0xb9, 0xc8, 0x84, 0x71, 0x1b, 0xe2, 0xd3, 0xc6,
	0x4f, 0xbc, 0xe0, 0x6f, 0x0d, 0x80, 0x4a, 0xe3, 0x3f, 0x86, 0xdb, 0x18, 0x44, 0x9e, 0xb2, 0x98,
	0xbb, 0x30, 0x5c, 0xd5, 0xf1, 0xf3, 0x5e, 0xf8, 0x56, 0x26, 0xe4, 0x09, 0x2a, 0x29, 0x8e, 0x27,
	0xb6, 0x05, 0x3e, 0xb6, 0x91, 0xd7, 0x27, 0x55, 0xcb, 0x7b, 0xa1, 0xbf, 0x36, 0xc7, 0xb2, 0xdd,
	0x43, 0x40, 0x34, 0x2a, 0x0b, 0xed, 0xd6, 0x68, 0x92, 0xfd, 0x66, 0x26, 0xa4, 0x2b, 0x99, 0x5b,
	0x60, 0x0c, 0xb8, 0x6e, 0x54, 0xb2, 0x4f, 0x54, 0x6b, 0x44, 0x8f, 0x12, 0x5b, 0x16, 0xd5, 0xd9,
	0x3f, 0x86, 0xdb, 0xc6, 0x66, 0x31, 0x2a, 0x0c, 0xd3, 0x26, 0xa2, 0xbd, 0x81, 0xb5, 0x68, 0x53,
	0x2d, 0xde, 0x72, 0xda, 0x53, 0x54, 0x9e, 0x89, 0x8c, 0x63, 0x35, 0xbe, 0x0f, 0xb7, 0x12, 0x9e,
	0x8a, 0xa2, 0x66, 0xdd, 0x25, 0xeb, 0x91, 0x85, 0x6b, 0x76, 0x5c, 0xb2, 0x49, 0xca, 0x2b, 0x3b,
	0xdb, 0x9a, 0x23, 0x0b, 0x3b, 0xbb, 0xe0, 0x2f, 0x4d, 0x68, 0x53, 0xc4, 0x6b, 0xd4, 0xe1, 0xad,
	0x53, 0x47, 0x8d, 0x87, 0x1a, 0x6b, 0x3c, 0xf4, 0x7f, 0x73, 0xe3, 0x7b, 0x30, 0x74, 0x07, 0xb9,
	0x3d, 0x0d, 0x1c, 0x83, 0x5b, 0xec, 0x8c, 0xce, 0x84, 0xf7, 0x61, 0xe4, 0x4c, 0xa6, 0x22, 0x4d,
	0x79, 0xe2, 0xf6, 0xa9, 0x9b, 0xf7, 0x82, 0x30, 0xdc, 0x8e, 0x56, 0x1b, 0xb1, 0x0b, 0xae, 0x19,
	0x1e, 0xef, 0xb4, 0x98, 0xdd, 0xb7, 0xbe, 0xd5, 0x3d, 0xb1, 0x2a, 0x7b, 0xbf, 0x78, 0xb0, 0xda,
	0xf7, 0xbd, 0xd7, 0x5c, 0x3f, 0x25, 0xc5, 0x8a, 0x0a, 0x3e, 0x80, 0x8d, 0x58, 0x73, 0x66, 0x5c,
	0x2e, 0xb3, 0x82, 0xae, 0x03, 0xcd, 0x70, 0x68, 0xd1, 0x33, 0xcb, 0x61, 0x1f, 0xc0, 0xc6, 0x22,
	0x4f, 0xea, 0x56, 0x60, 0xad, 0x2c, 0xea, 0xac, 0xb0, 0x2e, 0x97, 0xb9, 0xd0, 0xb5, 0xba, 0x0c,
	0x5c, 0x5d, 0x08, 0x2e, 0xeb, 0xb7, 0x0d, 0x6d, 0xa9, 0x90, 0xae, 0x6e, 0x91, 0xd6, 0x0a, 0x58,
	0x88, 0x89, 0x52, 0xe7, 0x58, 0x88, 0x4d, 0x4b, 0xa0, 0x28, 0x1e, 0x25, 0xc1, 0x29, 0xb4, 0x5e,
	0x15, 0x5c, 0xfb, 0x1b, 0xd0, 0x58, 0x95, 0xaf, 0x21, 0xe8, 0x98, 0xe5, 0x19, 0x13, 0xab, 0x63,
	0x96, 0x04, 0xff, 0x43, 0xd8, 0xa0, 0x41, 0x74, 0xc1, 0xb5, 0x98, 0x0a, 0x77, 0xac, 0xf6, 0xc2,
	0x11, 0xa1, 0x5f, 0x3a, 0x30, 0x78, 0x0c, 0x83, 0x27, 0x49, 0xa2, 0x0f, 0x85, 0xc4, 0x36, 0xf4,
	0x7d, 0x68, 0xb1, 0x24, 0xd1, 0x6e, 0x0b, 0xd3, 0x18, 0x77, 0xf5, 0xc2, 0x75, 0x45, 0x33, 0xc4,
	0x61, 0xf0, 0x19, 0xf4, 0x43, 0x66, 0xb8, 0xdd, 0xa8, 0xdf, 0x83, 0xfe, 0x52, 0xc8, 0x44, 0x2d,
	0x4f, 0x79, 0xec, 0xbc, 0xaa, 0x00, 0x9c, 0x2c, 0x17, 0x59, 0x39, 0x59, 0x2e, 0xb2, 0xe0, 0x33,
	0x18, 0x1e, 0x32, 0x29, 0xb9, 0x76, 0x4c, 0xf7, 0x43, 0xe8, 0xc7, 0x2c, 0xcb, 0x99, 0x98, 0x49,
	0x3c, 0x32, 0x90, 0x7e, 0x46, 0x44, 0x13, 0x4f, 0x1d, 0x1a, 0x56, 0xfa, 0xe0, 0x77, 0x0d, 0xe8,
	0x95, 0x38, 0x3a, 0x6b, 0xae, 0x72, 0xee, 0xd8, 0x90, 0xc6, 0x88, 0xa5, 0x4c, 0xce, 0x5c, 0x2e,
	0x68, 0x8c, 0x17, 0x1a, 0x91, 0x61, 0xbf, 0x2c, 0x74, 0xea, 0x0e, 0x93, 0x1e, 0x01, 0xaf, 0x34,
	0xb5, 0x9e, 0x99, 0x2f, 0xb2, 0x89, 0xc4, 0x5c, 0xa1, 0x81, 0xed, 0xdd, 0xe1, 0x0a, 0x44, 0xa3,
	0x7b, 0x30, 0x60, 0xda, 0x88, 0x38, 0xb5, 0xdf, 0xb0, 0x1d, 0x0c, 0x0e, 0x42, 0x83, 0x3b, 0xd0,
	0x9b, 0xcc, 0xa2, 0x58, 0xa5, 0x4a, 0xbb, 0xde, 0xed, 0x4e, 0x66, 0x4f, 0x51, 0xc4, 0xd5, 0xed,
	0x9e, 0xc3, 0x3c, 0x74, 0xc9, 0x55, 0xbb, 0x09, 0x5f, 0x2e, 0x32, 0x6c, 0xa8, 0x6b, 0xbc, 0x60,
	0x77, 0xf0, 0xb0, 0xa8, 0x13, 0xc2, 0x1e, 0x0c, 0xb9, 0x4c, 0x2a, 0x1b, 0xdb, 0x9a, 0xc0, 0x65,
	0x52, 0x6e, 0xf1, 0x7f, 0x79, 0x30, 0x3c, 0x66, 0xfa, 0x9c, 0x1b, 0x97, 0xd5, 0x07, 0xb0, 0x45,
	0x67, 0x7d, 0x34, 0xe5, 0x3c, 0xd2, 0xd8, 0xb1, 0xfc, 0x80, 0x12, 0xd5, 0x0a, 0x37, 0x48, 0xf1,
	0x82, 0x73, 0xac, 0xe1, 0xf3, 0x03, 0x34, 0x35, 0xaf, 0x99, 0x36, 0xac, 0xa9, 0x59, 0x37, 0x7d,
	0x04, 0xdb, 0x2b, 0xea, 0xab, 0x5b, 0x37, 0xc9, 0x7a, 0xab, 0xd4, 0xd5, 0x27, 0x0c, 0x62, 0x56,
	0xcc, 0x23, 0x77, 0xba, 0xb4, 0xa9, 0xbc, 0x1b, 0xd5, 0x29, 0x80, 0xcf, 0x8e, 0x10, 0xd0, 0xc4,
	0x9e, 0x23, 0xfe, 0xc7, 0x30, 0x2c, 0x0c, 0x9e, 0xb5, 0x6e, 0x46, 0xe7, 0xc6, 0x19, 0x03, 0xb2,
	0xb1, 0x53, 0x82, 0xdf, 0x7b, 0xd0, 0x5f, 0xa9, 0xfe, 0xdb, 0x7d, 0xf4, 0x5d, 0x00, 0xab, 0x92,
	0x2c, 0xe3, 0xae, 0x43, 0xfa, 0x84, 0xbc, 0x64, 0x19, 0xaf, 0xd4, 0xb1, 0x4a, 0xec, 0xe5, 0x74,
	0xe4, 0xd4, 0x4f, 0x55, 0x52, 0x53, 0xd3, 0x06, 0x69, 0xd5, 0x66, 0xe3, 0x06, 0x42, 0x96, 0x2b,
	0x62, 0x96, 0xf2, 0x68, 0xca, 0x62, 0xa3, 0xec, 0x1d, 0xab, 0x15, 0x0e, 0x08, 0x7b, 0x41, 0x50,
	0xf0, 0x8f, 0x16, 0x8c, 0xc8, 0xd1, 0x63, 0x6e, 0x18, 0x3e, 0xe3, 0xbe, 0x0d, 0x67, 0xc9, 0x9b,
	0xe6, 0x75, 0x6f, 0x70, 0x6b, 0xb0, 0x99, 0x7d, 0x45, 0xf4, 0x43, 0x1a, 0xfb, 0x3f, 0x87, 0x41,
	0xc2, 0x8b, 0x58, 0x8b, 0x9c, 0xd8, 0xbc, 0x4d, 0x27, 0xf2, 0xdd, 0x2a, 0xb3, 0xa5, 0x57, 0xe3,
	0x67, 0x95, 0x55, 0x58, 0x9f, 0x82, 0x8b, 0x0a, 0x29, 0xca, 0xe7, 0x9c, 0xed, 0xf3, 0x3e, 0x22,
	0x27, 0x25, 0xd1, 0xdb, 0x97, 0xc5, 0xda, 0xbd, 0xd1, 0xbe, 0x36, 0xdc, 0x79, 0xb8, 0x07, 0x83,
	0x58, 0xe8, 0x78, 0x91, 0x32, 0xf2, 0xc1, 0x5e, 0x22, 0xeb, 0x10, 0x6e, 0x97, 0x19, 0x2b, 0xa2,
	0x14, 0xb9, 0xc5, 0x3d, 0xc9, 0x7a, 0x33, 0x56, 0x58, 0xae, 0x59, 0x45, 0x9d, 0xaa, 0x99, 0x72,
	0x0f, 0x33, 0x1b, 0xf5, 0xe7, 0x6a, 0xa6, 0xf0, 0x06, 0xb8, 0xe4, 0x93, 0x42, 0x18, 0x4e, 0x84,
	0xdb, 0x0f, 0x4b, 0xd1, 0xff, 0x29, 0xf4, 0x35, 0xcf, 0x95, 0x36, 0x5c, 0x17, 0x3b, 0x43, 0xea,
	0xa9, 0x77, 0x6e, 0x88, 0x3c, 0x74, 0x36, 0x61, 0x65, 0xbd, 0xfb, 0x23, 0x18, 0xd4, 0x12, 0x82,
	0xec, 0xcb, 0xa5, 0x2b, 0x56, 0x83, 0x93, 0xfc, 0xf5, 0xdc, 0xd5, 0xa7, 0xf1, 0xf5, 0x7c, 0xf7,
	0x37, 0x1e, 0xf4, 0xca, 0xcf, 0xe0, 0xc5, 0xd3, 0x7e, 0xa8, 0xbc, 0xdb, 0x5b, 0xc9, 0xdf, 0x85,
	0x5e, 0xb9, 0x80, 0x9b, 0xba, 0x92, 0x91, 0x90, 0xca, 0x71, 0x44, 0xa1, 0xd8, 0xe2, 0x0e, 0x4b,
	0xf0, 0x14, 0xe3, 0xa9, 0x1b, 0x51, 0x2e, 0x5a, 0xeb, 0x46, 0x98, 0x8e, 0xe0, 0x18, 0xfc, 0x97,
	0xca, 0x88, 0xa9, 0x88, 0x29, 0xb5, 0x8e, 0x19, 0x7e, 0x0c, 0x23, 0x59, 0x43, 0x4b, 0xce, 0xdd,
	0xa2, 0x74, 0xd4, 0xed, 0xc3, 0x75, 0xbb, 0xe0, 0x4f, 0x1e, 0x0c, 0xeb, 0x7a, 0x7a, 0xdf, 0x09,
	0x93, 0xae, 0xde, 0x9d, 0x24, 0xdc, 0xc8, 0xc0, 0xd7, 0xf8, 0xb3, 0xf9, 0x1a, 0x7f, 0xae, 0x91,
	0x64, 0xeb, 0x7f, 0x92, 0x64, 0xfb, 0x1b, 0x90, 0x64, 0xe7, 0x35, 0x92, 0xfc, 0xbb, 0x07, 0xdb,
	0xa7, 0x22, 0xcb, 0x53, 0xfe, 0x15, 0x4b, 0x53, 0x6e, 0x9e, 0xb2, 0x34, 0x3d, 0x64, 0xf1, 0x39,
	0x96, 0x83, 0xfe, 0x86, 0xc4, 0x2a, 0x75, 0xb1, 0xac, 0x64, 0xec, 0xa9, 0x0b, 0xae, 0x8b, 0xf2,
	0xdd, 0xd2, 0x0f, 0x4b, 0xd1, 0xbf, 0x0b, 0x40, 0xcf, 0x82, 0x78, 0xce, 0x84, 0x2c, 0x63, 0xaa,
	0x10, 0x3c, 0x18, 0xd1, 0x99, 0xc2, 0xb0, 0x2c, 0xa7, 0x98, 0x9a, 0x61, 0x05, 0x60, 0x9a, 0x0a,
	0x31, 0x93, 0xee, 0x2c, 0xa1, 0x31, 0x62, 0x8b, 0xc5, 0xd1, 0x33, 0xb7, 0xb3, 0x68, 0x8c, 0xeb,
	0xb3, 0x38, 0xae, 0xed, 0xa7, 0x52, 0xc4, 0xa3, 0x55, 0xf3, 0x69, 0xf9, 0x10, 0xd3, 0x7c, 0x8a,
	0x15, 0xf2, 0xeb, 0x01, 0xba, 0xf7, 0xf0, 0xf5, 0x0b, 0x03, 0x2d, 0xb3, 0xba, 0xe7, 0xd1, 0xb8,
	0x7c, 0x95, 0xbb, 0x5b, 0x5e, 0x7b, 0x75, 0xa5, 0xab, 0x9e, 0x4e, 0xb6, 0x2a, 0xe5, 0x7d, 0xc9,
	0x87, 0x16, 0xee, 0x98, 0xd2, 0x7d, 0x62, 0xb3, 0x7b, 0x30, 0xa8, 0xdd, 0xa1, 0xca, 0x02, 0x54,
	0x17, 0x28, 0x34, 0xa8, 0x5d, 0x8c, 0xdc, 0xa5, 0x16, 0xaa, 0x4b, 0x51, 0xf0, 0x4f, 0x0f, 0xba,
	0x4f, 0xf2, 0x9c, 0x88, 0xbc, 0x96, 0x78, 0x6f, 0x3d, 0xf1, 0xf7, 0x60, 0xe0, 0x86, 0xd4, 0x4d,
	0x36, 0x0c, 0x70, 0x10, 0x76, 0xd3, 0x7b, 0x30, 0x4c, 0xd4, 0x52, 0xa6, 0x8a, 0x25, 0xb5, 0x7e,
	0x1b, 0x94, 0x18, 0x9a, 0xac, 0xc7, 0xd5, 0x5c, 0xc5, 0xb5, 0x03, 0xdd, 0x58, 0x65, 0x19, 0x5f,
	0xbd, 0xe4, 0x4b, 0x11, 0xb9, 0xc7, 0x0d, 0x23, 0x2e, 0xcb, 0xc7, 0xa2, 0x43, 0x9e, 0x4b, 0xea,
	0xa1, 0x94, 0x99, 0xa9, 0xd2, 0x99, 0x2b, 0xc9, 0x4a, 0xc6, 0x4e, 0xa9, 0xb2, 0xe0, 0x48, 0xad,
	0x86, 0x1c, 0x8e, 0x7f, 0xf9, 0xf0, 0x9b, 0xff, 0xc4, 0x9b, 0xf2, 0x49, 0x87, 0xa4, 0xc7, 0xff,
	0x0e, 0x00, 0x00, 0xff, 0xff, 0x79, 0x17, 0x7b, 0x69, 0x0f, 0x14, 0x00, 0x00,
}
